// Mocks generated by Mockito 5.4.5 from annotations
// in devhub/test/unit/infrastructure/network/interceptors/auth_interceptor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:devhub/core/data/key_value_store/key_value_storage.dart' as _i6;
import 'package:dio/src/dio_exception.dart' as _i4;
import 'package:dio/src/dio_mixin.dart' as _i2;
import 'package:dio/src/headers.dart' as _i5;
import 'package:dio/src/options.dart' as _i3;
import 'package:dio/src/redirect_record.dart' as _i9;
import 'package:dio/src/response.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInterceptorState_0<T> extends _i1.SmartFake
    implements _i2.InterceptorState<T> {
  _FakeInterceptorState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRequestOptions_1 extends _i1.SmartFake
    implements _i3.RequestOptions {
  _FakeRequestOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStackTrace_2 extends _i1.SmartFake implements StackTrace {
  _FakeStackTrace_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDioException_3 extends _i1.SmartFake implements _i4.DioException {
  _FakeDioException_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHeaders_4 extends _i1.SmartFake implements _i5.Headers {
  _FakeHeaders_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_5 extends _i1.SmartFake implements Uri {
  _FakeUri_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KeyValueStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyValueStorage extends _i1.Mock implements _i6.KeyValueStorage {
  MockKeyValueStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> put({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#put, [], {#key: key, #value: value}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> get({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [], {#key: key}),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> delete({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#key: key}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [RequestInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestInterceptorHandler extends _i1.Mock
    implements _i2.RequestInterceptorHandler {
  MockRequestInterceptorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.InterceptorState<dynamic>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i7.Future<_i2.InterceptorState<dynamic>>.value(
              _FakeInterceptorState_0<dynamic>(
                this,
                Invocation.getter(#future),
              ),
            ),
          )
          as _i7.Future<_i2.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(Invocation.getter(#isCompleted), returnValue: false)
          as bool);

  @override
  void next(_i3.RequestOptions? requestOptions) => super.noSuchMethod(
    Invocation.method(#next, [requestOptions]),
    returnValueForMissingStub: null,
  );

  @override
  void resolve(
    _i8.Response<dynamic>? response, [
    bool? callFollowingResponseInterceptor = false,
  ]) => super.noSuchMethod(
    Invocation.method(#resolve, [response, callFollowingResponseInterceptor]),
    returnValueForMissingStub: null,
  );

  @override
  void reject(
    _i4.DioException? error, [
    bool? callFollowingErrorInterceptor = false,
  ]) => super.noSuchMethod(
    Invocation.method(#reject, [error, callFollowingErrorInterceptor]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ErrorInterceptorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorInterceptorHandler extends _i1.Mock
    implements _i2.ErrorInterceptorHandler {
  MockErrorInterceptorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.InterceptorState<dynamic>> get future =>
      (super.noSuchMethod(
            Invocation.getter(#future),
            returnValue: _i7.Future<_i2.InterceptorState<dynamic>>.value(
              _FakeInterceptorState_0<dynamic>(
                this,
                Invocation.getter(#future),
              ),
            ),
          )
          as _i7.Future<_i2.InterceptorState<dynamic>>);

  @override
  bool get isCompleted =>
      (super.noSuchMethod(Invocation.getter(#isCompleted), returnValue: false)
          as bool);

  @override
  void next(_i4.DioException? error) => super.noSuchMethod(
    Invocation.method(#next, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void resolve(_i8.Response<dynamic>? response) => super.noSuchMethod(
    Invocation.method(#resolve, [response]),
    returnValueForMissingStub: null,
  );

  @override
  void reject(_i4.DioException? error) => super.noSuchMethod(
    Invocation.method(#reject, [error]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DioException].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioException extends _i1.Mock implements _i4.DioException {
  MockDioException() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.RequestOptions get requestOptions =>
      (super.noSuchMethod(
            Invocation.getter(#requestOptions),
            returnValue: _FakeRequestOptions_1(
              this,
              Invocation.getter(#requestOptions),
            ),
          )
          as _i3.RequestOptions);

  @override
  _i4.DioExceptionType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i4.DioExceptionType.connectionTimeout,
          )
          as _i4.DioExceptionType);

  @override
  StackTrace get stackTrace =>
      (super.noSuchMethod(
            Invocation.getter(#stackTrace),
            returnValue: _FakeStackTrace_2(
              this,
              Invocation.getter(#stackTrace),
            ),
          )
          as StackTrace);

  @override
  set stringBuilder(_i4.DioExceptionReadableStringBuilder? _stringBuilder) =>
      super.noSuchMethod(
        Invocation.setter(#stringBuilder, _stringBuilder),
        returnValueForMissingStub: null,
      );

  @override
  _i4.DioException copyWith({
    _i3.RequestOptions? requestOptions,
    _i8.Response<dynamic>? response,
    _i4.DioExceptionType? type,
    Object? error,
    StackTrace? stackTrace,
    String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #requestOptions: requestOptions,
              #response: response,
              #type: type,
              #error: error,
              #stackTrace: stackTrace,
              #message: message,
            }),
            returnValue: _FakeDioException_3(
              this,
              Invocation.method(#copyWith, [], {
                #requestOptions: requestOptions,
                #response: response,
                #type: type,
                #error: error,
                #stackTrace: stackTrace,
                #message: message,
              }),
            ),
          )
          as _i4.DioException);
}

/// A class which mocks [Response].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponse<T> extends _i1.Mock implements _i8.Response<T> {
  MockResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set data(T? _data) => super.noSuchMethod(
    Invocation.setter(#data, _data),
    returnValueForMissingStub: null,
  );

  @override
  _i3.RequestOptions get requestOptions =>
      (super.noSuchMethod(
            Invocation.getter(#requestOptions),
            returnValue: _FakeRequestOptions_1(
              this,
              Invocation.getter(#requestOptions),
            ),
          )
          as _i3.RequestOptions);

  @override
  set requestOptions(_i3.RequestOptions? _requestOptions) => super.noSuchMethod(
    Invocation.setter(#requestOptions, _requestOptions),
    returnValueForMissingStub: null,
  );

  @override
  set statusCode(int? _statusCode) => super.noSuchMethod(
    Invocation.setter(#statusCode, _statusCode),
    returnValueForMissingStub: null,
  );

  @override
  set statusMessage(String? _statusMessage) => super.noSuchMethod(
    Invocation.setter(#statusMessage, _statusMessage),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Headers get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: _FakeHeaders_4(this, Invocation.getter(#headers)),
          )
          as _i5.Headers);

  @override
  set headers(_i5.Headers? _headers) => super.noSuchMethod(
    Invocation.setter(#headers, _headers),
    returnValueForMissingStub: null,
  );

  @override
  bool get isRedirect =>
      (super.noSuchMethod(Invocation.getter(#isRedirect), returnValue: false)
          as bool);

  @override
  set isRedirect(bool? _isRedirect) => super.noSuchMethod(
    Invocation.setter(#isRedirect, _isRedirect),
    returnValueForMissingStub: null,
  );

  @override
  List<_i9.RedirectRecord> get redirects =>
      (super.noSuchMethod(
            Invocation.getter(#redirects),
            returnValue: <_i9.RedirectRecord>[],
          )
          as List<_i9.RedirectRecord>);

  @override
  set redirects(List<_i9.RedirectRecord>? _redirects) => super.noSuchMethod(
    Invocation.setter(#redirects, _redirects),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> get extra =>
      (super.noSuchMethod(
            Invocation.getter(#extra),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  set extra(Map<String, dynamic>? _extra) => super.noSuchMethod(
    Invocation.setter(#extra, _extra),
    returnValueForMissingStub: null,
  );

  @override
  Uri get realUri =>
      (super.noSuchMethod(
            Invocation.getter(#realUri),
            returnValue: _FakeUri_5(this, Invocation.getter(#realUri)),
          )
          as Uri);
}
